server:
  port: 8080
  
  ssl:
    key-store: ${ssl.key.location}
    key-store-password: ${ssl.key.secret}
    keyStoreType: ${ssl.key.type}
    keyAlias: ${ssl.key.alias}


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
  
eureka:
  instance:
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 5
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  actuator:
    sensitive: false

zuul:
  routes:
    registration-service:
        serviceId: registration-service
        path: /registerservice/**
        
    auth-service:
        serviceId: auth-service
        path: /auth/login
        
    jobapplication-service:
        serviceId: jobapplication-service
        path: /jobapplication/**
  sensitive-headers: 

  prefix: /api
  
  
---
spring:
  profiles: local
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
