server:
  port: 9876
  
eureka:
  instance:
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
      
spring:
  datasource:
    url: jdbc:mysql://gortz.org:6603/recruitmentsystem_jobapplication?verifyServerCertificate=false&useSSL=true
    username: recruitment_jobapplication
    password: 5D783c3b%0SmFMU09JRN
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialize: false
