server:
  port: 9876
  
eureka:
  instance:
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
      
spring:
  datasource:
    url:  ${database.url}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialize: false
    
---
# Properties in case developer is using Docker Toolbox
# Default zone: Define --docker-host as commandline property when starting application to enter custom URI or default will be used
spring:
  profiles: docker-toolbox
eureka:
  client:
    serviceUrl:
      defaultZone: ${docker-host:http://192.168.99.100}:9090/eureka/
---
# Properties in case developer is running services locally or running in docker for linux or mac, for windows use docker-toolbox
spring:
  profiles: local
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/

