server:
  port: 9876
  
eureka:
  instance:
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
      
spring:
  datasource:
    url: jdbc:mysql://gortz.org:6603/recruitmentsystem_jobapplication?verifyServerCertificate=false&useSSL=true
    username: recruitment_jobapplication
    password: 5D783c3b%0SmFMU09JRN
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialize: false
    
---
# Properties in case developer is using Docker Toolbox
# Config-uri: Define --docker-host as commandline property when starting application to enter custom URI or default will be used
spring:
  profiles: docker-toolbox
  cloud:
      config:
        uri: ${docker-host:http://192.168.99.100}:9999
---
# Properties in case developer is running services locally or running in docker for linux or mac, for windows use docker-toolbox
spring:
  profiles: local
  cloud:
      config:
        uri: http://localhost:9999

